djangoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('pizza/', include('pizza.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns = [
    path('', include('studenci.urls')),
    path('pizza/', include('pizza.urls')),
    #path('studenci/', include('studenci.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('ankiety', include('ankiety.urls')),
]

pizza/urls.py
from django.urls import path
from . import views

app_name = 'pizza'
urlpatterns = [
    path('', views.index, name='index'),
    path('pizza/dodaj', views.dodajPizza, name='pizza_add'),
    path('skladnik/dodaj', views.dodajSkladnik, name='skladnik_add'),
]

studenci/urls.py
from django.urls import path
from . import views
from django.views.generic import ListView
from studenci.models import Miasto

app_name = 'studenci'
urlpatterns = [
    path('', views.index, name='index'),
    path('miasta/', ListView.as_view(model=Miasto,context_object_name='miasta',template_name='studenci/lista_miast.html'), name='miasta_lista'),
    path('miasta/dodaj', views.miasta, name='miasta_dodaj'),
    path('uczelnie/lista', views.ListaUczelni.as_view(), name='uczelnie_lista'),
    path('miasta/create', views.DodajMiasto.as_view(), name='miasta_create'),
    path('uczelnie/create', views.DodajUczelnie.as_view(), name='uczelnia_create'),
    path('uczelnie/', views.uczelnie, name='uczelnie'),
    path('login/', views.loguj_studenta, name='login'),
    path('uczelnie/edytuj/<int:pk>', views.EdytujUczelnie.as_view(), name='uczelnie_edytuj'),
    path('uczelnie/usun/<int:pk>', views.UsunUczelnie.as_view(), name='uczelnie_usun'),
    path('miasta/usun/<int:pk>', views.UsunMiasta.as_view(), name='miasta_usun'),
    path('miasta/edytuj/<int:pk>', views.EdytujMiasta.as_view(), name='miasta_edytuj'),
]

studenci/models.py
from django.db import models


class Uczelnia(models.Model):
    nazwa = models.CharField(verbose_name='uczelnia', max_length=30)

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name_plural = "uczelnie"

class Miasto(models.Model):
    nazwa = models.CharField(verbose_name='miasto', max_length=30)
    kod = models.CharField(max_length=6, help_text="Wpisz kod pocztowy")

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name_plural = "miasta"

class Student(models.Model):
    imie = models.CharField(max_length=30)
    nazwisko = models.CharField(max_length=30)
    uczelnia = models.ForeignKey(Uczelnia, on_delete=models.SET_NULL, null=True)
    miasto = models.ForeignKey(Miasto, on_delete=models.SET_NULL, null=True)
    roks = models.CharField('rok studiów', max_length=3, blank=True, default='')
    dochod = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __str__(self):
        return self.imie + ' ' + self.nazwisko

    class Meta:
        verbose_name_plural = "studenci"

studenci/forms.py
from django import forms
from django.forms import ModelForm
from studenci.models import Uczelnia, Miasto

class UczelniaModelForm(ModelForm):
        class Meta:
            model = Uczelnia
            fields = ('nazwa',)


class MiastoModelForm(ModelForm):
    class Meta:
        model = Miasto
        fields = ('nazwa','kod',)

class UserLoginForm(forms.Form):
    login = forms.CharField(label="Twój login", max_length=20, widget=forms.TextInput())

class UczelniaForm(forms.Form):
    nazwa = forms.CharField(label="twoja szkoła", max_length=50, widget=forms.TextInput())

class MiastaForm(forms.Form):
    nazwa = forms.CharField(label="Podaj miasto", max_length=50, widget=forms.TextInput())
    kod = forms.CharField(label="Podaj kod", max_length=10, widget=forms.TextInput())

studenci/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse, reverse_lazy

from studenci.models import Miasto, Uczelnia
from studenci.forms import UserLoginForm, UczelniaForm, MiastaForm, UczelniaModelForm, MiastoModelForm

from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.edit import DeleteView


def index(request):
    # return HttpResponse("<h1>Witaj wsród sudentów!</h1>")
    return render(request, 'studenci/index.html')

def komunikat(request):
    return HttpResponse("<h1>Komunikat!</h1>")
    # return render(request, 'pizza/komunikat.html'

def miasta(request):
    if request.method == 'POST':
        #nazwa = request.POST.get('nazwa', '')
        #kod = request.POST.get('kod', '')
        #if len(nazwa.strip()) and len(kod.strip()):
        form = MiastaForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            m = Miasto(nazwa=form.cleaned_data['nazwa'], kod=form.cleaned_data['kod'])
            m.save()
            messages.success(request, "Dobrze!!!")
            return redirect(reverse('studenci:miasta'))
        else:
            messages.error(request, "Ło ty oszukisto!!!")
    else:
        form = MiastaForm()
    miasta = Miasto.objects.all()
    kontekst = {'miasta': miasta, 'form': form}
    return render(request, 'studenci/miasta.html', kontekst)

def uczelnie(request):
    if request.method == 'POST':
        form = UczelniaForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            u = Uczelnia(nazwa=form.cleaned_data['nazwa'])
            u.save()
            messages.success(request, "Dobrze!!!")
            return redirect(reverse('studenci:uczelnie'))
        else:
            messages.error(request, "Ło ty oszukisto!!!")

    else:
        form = UczelniaForm()
    uczelnie = Uczelnia.objects.all()
    kontekst = {'uczelnie': uczelnie, 'form': form}
    if request.user.has_perm('studenci.add_uczelnia'):
     return render(request, 'studenci/uczelnie.html', kontekst)
    else:
        messages.info(request, "Nie możesz dodawać uczelni")
        return redirect(reverse('studenci:index'))

class ListaUczelni(ListView):
    model = Uczelnia
    context_object_name = 'uczelnie'
    template_name='studenci/lista_uczelni.html'


@method_decorator(login_required, name='dispatch')
class DodajMiasto(CreateView):
    model = Miasto
    fields = ('nazwa', 'kod')
    template_name = 'studenci/dodaj_miasto.html'
    success_url = reverse_lazy('studenci:miasta_lista')

class DodajUczelnie(CreateView):
    model = Uczelnia
    fields = ('nazwa',)
    template_name = 'studenci/dodaj_uczelnie.html'
    success_url = reverse_lazy('studenci:uczelnie_lista')

    def get_context_data(self, **kwargs):
        context = super(DodajUczelnie, self).get_context_data(**kwargs)
        context['uczelnie'] = Uczelnia.objects.all()
        return context

    def form_valid(self, form):
        messages.success(self.request, "Dodano miasto")
        return super().form_valid(form)

def loguj_studenta(request):
    if request.method == 'POST':
        pass
    else:
        form = UserLoginForm()
    kontekst = {'form': form}
    return render(request, 'studenci/login.html', kontekst)

from django.contrib.messages.views import SuccessMessageMixin

@method_decorator(login_required, name='dispatch')
class EdytujUczelnie(SuccessMessageMixin, UpdateView):
    model = Uczelnia
    form_class = UczelniaModelForm
    template_name = 'studenci/uczelnie.html'
    success_url = reverse_lazy('studenci:uczelnie_lista')
    success_message = 'Uczelnię zaktualizowano!'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['uczelnie'] = Uczelnia.objects.all()
        return context

class UsunUczelnie(DeleteView):
    model = Uczelnia
    success_url = reverse_lazy('studenci:uczelnie_lista')

@method_decorator(login_required, name='dispatch')
class EdytujMiasta(SuccessMessageMixin, UpdateView):
    model = Miasto
    form_class = MiastoModelForm
    template_name = 'studenci/miasta.html'
    success_url = reverse_lazy('studenci:miasta_lista')
    success_message = 'miasta zaktualizowano!'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['miasta'] = Miasto.objects.all()
        return context

class UsunMiasta(DeleteView):
     model = Miasto
     success_url = reverse_lazy('studenci:miasta_lista')

studenci/templates/studenci/dodaj_miasto.html
{% extends 'szablon.html' %}
{% block naglowek %}Miasta{% endblock naglowek %}
{% block tresc %}

<h2>Dodaj miasto</h2>
    <form  method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zapisz">
    </form>
{% endblock tresc %}

studenci/templates/studenci/dodaj_uczelnie.html
{% extends 'szablon.html' %}
{% block naglowek %}Uczelnie{% endblock naglowek %}
{% block tresc %}

<h2>Dodaj uczelnie</h2>
    <form  method="POST">
        {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" value="Zapisz">
    </form>


{% endblock tresc %}

studenci/templates/studenci/index.html
{% extends 'szablon.html' %}
{% block naglowek %}Studenci{% endblock naglowek %}
{% block tresc %}
<p>Portal dla studentów.</p>
{% endblock tresc %}

studenci/templates/studenci/lista_miast.html
{% extends 'szablon.html' %}

{% block naglowek %}Miasta{% endblock naglowek %}
{% block tresc %}
<h2>Lista miast</h2>
<ol>
    {% for miasto in miasta %}
        <li>{{ miasto.nazwa }}&nbsp;{{ miasto.kod }} - <a href="{% url 'studenci:miasta_usun' miasto.id %}">Usuń</a>, <a href="{% url 'studenci:miasta_edytuj' miasto.id %}">Edytuj</a></li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/lista_uczelni.html
{% extends 'szablon.html' %}

{% block naglowek %}Uczelnie{% endblock naglowek %}
{% block tresc %}
<h2>Lista uczelni</h2>
<ol>
    {% for uczelnia in uczelnie %}
        <li>{{ uczelnia.nazwa }} - <a href="{% url 'studenci:uczelnie_usun' uczelnia.id %}">Usuń</a>, <a href="{% url 'studenci:uczelnie_edytuj' uczelnia.id %}">Edytuj</a></li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/lista_uczelnie.html
{% extends 'szablon.html' %}

{% block naglowek %}Uczelnie{% endblock naglowek %}
{% block tresc %}
<h2>Lista uczelni</h2>
<ol>
    {% for uczelnia in uczelnie %}
        <li>{{ uczelnia.nazwa }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/login.html
{% extends 'szablon.html' %}
{% block naglowek %}studenci-logowanie{% endblock naglowek %}
{% block tresc %}
    <form action="." method="POST">
        {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" value="Zapisz" class="btn">
    </form>
{% endblock tresc %}

studenci/templates/studenci/miasta.html
{% extends 'szablon.html' %}

<title>{% block tytul %}Lista miast{% endblock tytul %}</title>
{% block naglowek %}Miasta{% endblock naglowek %}
{% block tresc %}
    {% load crispy_forms_tags %}
<h2>Dodaj miasto</h2>
    {% if user.is_authenticated %}
        {% if perms.studenci.add_miasto %}
        <form method="POST">
        {% csrf_token %}
            {{ form|crispy }}
            <br>
            <input type="submit" value="Zapisz">
    </form>
    {% else %}
    <div class="well">Nie możesz dodawać miast</div>
        {% endif %}
    {% endif %}
<h2>Lista miast</h2>
<ol>
    {% for miasto in miasta %}
        <li>{{ miasto.nazwa }}&nbsp;{{ miasto.kod }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/miasto.html
{% extends 'szablon.html' %}

<title>{% block tytul %}Lista miast{% endblock tytul %}</title>

{% block naglowek %}miasta{% endblock naglowek %}
{% block tresc %}
<h2>Dodaj miasto</h2>
    <form action="." method="POST">
        {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" value="Zapisz">
    </form>

<h2>Lista miast</h2>
<ol>
    {% for miasto in miasta %}
        <li>{{ miasto.nazwa }} - <a href="{% url 'studenci:miasta_edytuj' miasto.id %}">Edytuj</a></li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/miasto_confirm_delete.html
{% extends 'szablon.html' %}
{% block naglowek %}miasta{% endblock naglowek %}
{% block tresc %}
<h2>Usuwanie miasta</h2>
    <form method="POST">
        {% csrf_token %}
        <p class = "lead"> Czy na pewno chcesz usunąć miasto:<br>
            {{ object.nazwa }}?
        </p>
        {{ form.as_p }}
        <input type="submit" value="Zapisz">
    </form>

{% endblock tresc %}

studenci/templates/studenci/uczelnia.html
{% extends 'szablon.html' %}
{% block naglowek %}uczelnia{% endblock naglowek %}
{% block tresc %}
    <form action="." method="POST">
        {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" value="Zapisz" class="btn">
    </form>
{% endblock tresc %}

studenci/templates/studenci/uczelnia_confirm_delete.html
{% extends 'szablon.html' %}
{% block naglowek %}Uczelnie{% endblock naglowek %}
{% block tresc %}
<h2>Usuwanie uczelni</h2>
    <form method="POST">
        {% csrf_token %}
        <p class = "lead"> Czy na pewno chcesz usunąć uczelnię:<br>
            {{ object.nazwa }}?
        </p>
        {{ form.as_p }}
        <input type="submit" value="Zapisz">
    </form>

{% endblock tresc %}

studenci/templates/studenci/uczelnie.html
{% extends 'szablon.html' %}

<title>{% block tytul %}Lista uczelnie{% endblock tytul %}</title>

{% block naglowek %}Uczelnie{% endblock naglowek %}
{% block tresc %}
    {% load crispy_forms_tags %}
<h2>Dodaj uczelnie</h2>
    <form  method="POST">
        {% csrf_token %}
            {{ form|crispy }}
            <br>
            <input type="submit" value="Zapisz">
    </form>

<h2>Lista uczelni</h2>
<ol>
    {% for uczelnia in uczelnie %}
        <li>{{ uczelnia.nazwa }} - <a href="{% url 'studenci:uczelnie_edytuj' uczelnia.id %}">Edytuj</a></li>
    {% endfor %}
</ol>
{% endblock tresc %}