ankiety/urls.py
from django.urls import path
from . import views

app_name = 'ankiety'
urlpatterns = [
    path('', views.ListaPytan.as_view(), name='lista_pytan'),
    path('pytanie/glosuj/<int:pk>', views.pytanie_glosuj, name='pytanie-glosuj'),
]

djangoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('pizza/', include('pizza.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns = [
    path('', include('studenci.urls')),
    path('pizza/', include('pizza.urls')),
    #path('studenci/', include('studenci.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('ankiety', include('ankiety.urls')),
]

pizza/urls.py
from django.urls import path
from . import views

app_name = 'pizza'
urlpatterns = [
    path('', views.index, name='index'),
    path('pizza/dodaj', views.dodajPizza, name='pizza_add'),
    path('skladnik/dodaj', views.dodajSkladnik, name='skladnik_add'),
]

studenci/urls.py
from django.urls import path
from . import views
from django.views.generic import ListView
from studenci.models import Miasto

app_name = 'studenci'
urlpatterns = [
    path('', views.index, name='index'),
    path('miasta/', ListView.as_view(model=Miasto,context_object_name='miasta',template_name='studenci/lista_miast.html'), name='miasta_lista'),
    path('miasta/dodaj', views.miasta, name='miasta_dodaj'),
    path('uczelnie/lista', views.ListaUczelni.as_view(), name='uczelnie_lista'),
    path('miasta/create', views.DodajMiasto.as_view(), name='miasta_create'),
    path('uczelnie/create', views.DodajUczelnie.as_view(), name='uczelnia_create'),
    path('uczelnie/', views.uczelnie, name='uczelnie'),
    path('login/', views.loguj_studenta, name='login'),
    path('uczelnie/edytuj/<int:pk>', views.EdytujUczelnie.as_view(), name='uczelnie_edytuj'),
    path('uczelnie/usun/<int:pk>', views.UsunUczelnie.as_view(), name='uczelnie_usun'),
    path('miasta/usun/<int:pk>', views.UsunMiasta.as_view(), name='miasta_usun'),
    path('miasta/edytuj/<int:pk>', views.EdytujMiasta.as_view(), name='miasta_edytuj'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
	path('', views.index, name='index'),
    path('rejestruj/', views.rejestruj, name='rejestruj'),
    path('loguj/', views.loguj_user, name='loguj'),
    path('wyloguj/', views.wyloguj_user, name='wyloguj'),
]

templates/szablon.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block tytul %}Projekt Django{% endblock tytul %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light">
        <a class="navbar-brand" href="http://lo1.sandomierz.pl">I LO CG</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Pizza</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'pizza:index' %}" class="dropdown-item">Strona główna</a>
                        <a href="{% url 'pizza:pizza_add' %}" class="dropdown-item">Dodaj pizzę</a>
                        <a href="{% url 'pizza:skladnik_add' %}" class="dropdown-item">Dodaj składnik</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Studenci</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'studenci:index' %}" class="dropdown-item">Strona główna</a>
                        <a href="{% url 'studenci:miasta_dodaj' %}" class="dropdown-item">Dodaj miasto</a>
                        <a href="{% url 'studenci:miasta_create' %}" class="dropdown-item">Utwórz miasto</a>
                        <a href="{% url 'studenci:uczelnia_create' %}" class="dropdown-item">Utwórz uczelnie</a>
                        <a href="{% url 'studenci:miasta_lista' %}" class="dropdown-item">Lista miast</a>
                        <a href="{% url 'studenci:uczelnie' %}" class="dropdown-item">Dodaj uczelnie</a>
                        <a href="{% url 'studenci:uczelnie_lista' %}" class="dropdown-item">Lista uczelni</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Ankiety</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'ankiety:lista_pytan' %}" class="dropdown-item">Lista pytan</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Użytkownik</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'users:index' %}" class="dropdown-item">Strona główna</a>
                        {% if not user.is_authenticated %}
                            <a href="{% url 'users:rejestruj' %}" class="dropdown-item">Załóż konto</a>
                            <a href="{% url 'users:loguj' %}" class="dropdown-item">Zaloguj</a>
                        {% else %}
                            <a href="{% url 'users:wyloguj' %}" class="dropdown-item">Wyloguj</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col">
<h1>{% block naglowek %}Projekt Django{% endblock naglowek %}</h1>
{% block komunikaty %}
{% if messages %}
    <ul>
    {% for komunikat in messages %}
        <li>{{ komunikat }}</li>
    {% endfor %}
    </ul>
{% endif %}
{% endblock komunikaty %}
{% block tresc %}
{% endblock tresc %}
            </div>
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>